### ISSUE TITLE
[Feature request]: improve site

### ISSUE THREAD

**Issue by ghost** [gnome-mpv/gnome-mpv.github.io#1]
_http://gnome-mpv.github.io/ a nightmare._
_It is necessary to improve the website._
_Player good, bad site._

_P.S. https://mpv.io/ nicely done website._
_P.P.S. Sorry for my bad English._

**Comment by gnome-mpv** [comment]
https://github.com/gnome-mpv/gnome-mpv.github.io/commit/c92709c0fae2afa94629ca59b87736a65171c4fc
